<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(NetFrameworkTestVersion);$(NetCoreTestVersion)</TargetFrameworks>
    <!-- Temporarily commented out to enable test discovery -->
    <!--<OutputType>Exe</OutputType>
    <StartupObject>Akka.Logger.Serilog.Tests.Generator.Program</StartupObject>-->
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Akka.TestKit.Xunit2" />
    <PackageReference Include="Akka.Cluster" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Akka.Logger.Serilog\Akka.Logger.Serilog.csproj" />
    <None Update="TestFiles\**\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
