# Release task for PbLib projects
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference

pool:
  vmImage: windows-latest
  demands: Cmd

trigger:
  branches:
    include:
      - refs/tags/*
pr: none

variables:
  - group: nugetKeys #create this group with SECRET variables `nugetKey`
  - name: githubConnectionName
    value: AkkaDotNet_Releases #replace this
  - name: projectName
    value: Akka.Logger.Serilog #replace this
  - name: githubRepositoryName
    value: akkadotnet/Akka.Logger.Serilog #replace this

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 7 SDK 7.0.x'
  inputs:
    version: 7.0.x
- task: UseDotNet@2
  displayName: 'Use .NET Core Runtime 6.0.x'
  inputs:
    packageType: runtime
    version: 6.0.x
- task: UseDotNet@2
  displayName: 'Use .NET Core Runtime 3.1.x'
  inputs:
    packageType: runtime
    version: 3.1.x

- task: BatchScript@1
  displayName: 'FAKE Build'
  inputs:
    filename: build.cmd
    arguments: 'All SignClientUser=$(signingUsername) SignClientSecret=$(signingPassword) nugetpublishurl=https://www.nuget.org/api/v2/package nugetkey=$(nugetKey)'

- task: GitHubRelease@0
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: $(githubConnectionName)
    repositoryName: $(githubRepositoryName)
    title: '$(projectName) v$(Build.SourceBranchName)'
    releaseNotesFile: 'RELEASE_NOTES.md'
    assets: |
     bin\nuget\*.nupkg
