<Project>
  <PropertyGroup>
    <PackageTags>akka;actors;actor model;Akka;concurrency;serilog</PackageTags>
    <Copyright>Copyright © 2013-2023 Akka.NET Team</Copyright>
    <Authors>Akka.NET Team</Authors>
    <PackageReleaseNotes>[Update Akka.Hosting to 1.5.25](https://github.com/akkadotnet/akka.net/releases/tag/1.5.25)
[implicitly convert regular `BusLogger` to `SerilogLoggingAdapter` when `ForContext` is called](https://github.com/akkadotnet/Akka.Logger.Serilog/pull/285)
As of Akka.Logger.Serilog v1.5.25, you can now do the following:
```csharp
var log = Context.GetLogger()
.ForContext("Address", "No. 4 Privet Drive")
.ForContext("Town", "Little Whinging")
.ForContext("County", "Surrey")
.ForContext("Country", "England");
log.Info("My boss makes me use {Semantic} logging", "semantic");
```
And it will work without having to explicitly call `Context.GetLogger&lt;SerilogLoggingAdapter&gt;()` first.</PackageReleaseNotes>
    <VersionPrefix>1.5.57</VersionPrefix>
    <PackageProjectUrl>https://github.com/akkadotnet/Akka.Logger.Serilog</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <LangVersion>12</LangVersion>
  </PropertyGroup>
  <PropertyGroup>
    <AkkaVersion>1.5.58</AkkaVersion>
    <AkkaHostingVersion>1.5.58</AkkaHostingVersion>
    <NetCoreTestVersion>net8.0</NetCoreTestVersion>
    <NetFrameworkTestVersion>net471</NetFrameworkTestVersion>
    <NetStandardLibVersion>netstandard2.0</NetStandardLibVersion>
  </PropertyGroup>
  <PropertyGroup>
    <!-- Optional: Publish the repository URL in the built .nupkg (in the NuSpec <Repository> element) -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <!-- Optional: Embed source files that are not tracked by the source control manager in the PDB -->
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <!-- Optional: Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>
</Project>